import numpy as np
import pandas as pd
from loguru import logger

import src.preprocessing.functions as preprocessing_functions
from src.global_vars import BASE_DATA_DIR


def aitchison_mixup(X_train, y_train, n_aug_per_class=5000, weight=0.5):
    """Applies Aitchison Mixup to some training data.

    Args:
        X_train: model inputs
        y_train: model outputs
        n_aug_per_class: the number of augmented samples to generate per class.
        weight: the total weight of all the augmented data generated.
            For example, if weight=0.5, then all the augmented data will
            weigh the same as all the original training data.
            Typically, this means the synthetic samples are downweighted
            relative to the original data.
        
    Returns:
        X_aug: model inputs including both those from the original
            training data and those generated by data augmentation.
        y_aug: model outputs including both those from the original
            training data and those generated by data augmentation.
        w_aug: sample weights for each sample in X_aug and y_aug.
            Typically, the sample weights corresponding to samples
            from the original training data will have high weight,
            those corresponding to synthetic datapoints will have
            low weight.
    """

    X = np.empty((0, X_train.shape[1]))
    y = np.empty((0,))
    w = np.ones_like(y)

    for val in y_train.unique():
        idxs = y_train == val
        X_temp = X_train[idxs, :]
        n = X_temp.shape[0]

        lam = np.random.rand(n_aug_per_class).reshape([-1, 1])
        idx1 = np.random.choice(n, size=n_aug_per_class)
        idx2 = np.random.choice(n, size=n_aug_per_class)

        # Take convex combination
        X_aug = lam * X_temp[idx1, :] + (1 - lam) * X_temp[idx2, :]

        X = np.concatenate([X, X_aug], axis=0)
        y = np.concatenate([y, np.repeat(val, n_aug_per_class)])
        w = np.concatenate([w, np.repeat(weight / (1 - weight) * X_train.shape[0] / n_aug_per_class, n_aug_per_class)])
    
    # Shuffle data
    n = X.shape[0]
    idx = np.arange(n)
    np.random.shuffle(idx)
    
    return X[idx], y[idx], w[idx]

def preprocess_data(
    do_prevalence_and_abundance_filtering: bool,
    normalize_and_transform: bool,
    title_addition: str,
    tax_level: str = "species",
    augment_data: bool = False,
) -> None:
    data_root_dir = f"{BASE_DATA_DIR}/sun_et_al_data/"
    columns_to_keep = ["Sample", "Group", "Project", "Project_1"]
    studies_to_remove = ["LiS_2021a", "LiS_2021b"]
    abundance_filtering_threshold = 0.0001

    # Get sample group data
    sample_group = pd.read_table(f"{data_root_dir}/sample.group", sep="\t", header=0)
    # Remove studies
    logger.info(f"sample_group.shape before removal of studies: {sample_group.shape}")
    sample_group = sample_group[~sample_group["Project_1"].isin(studies_to_remove)]
    logger.info(f"sample_group.shape after removal of studies: {sample_group.shape}")

    # Keep recommended columns
    # logger.info(f"sample_group.shape before column removal: {sample_group.shape}")
    # sample_group = sample_group[columns_to_keep]
    # logger.info(f"sample_group_useful.shape after column removal: {sample_group.shape}")
    # Set index to Sample
    sample_group = sample_group.set_index("Sample")
    logger.info(f"sample_group_useful.shape after setting index: {sample_group.shape}")

    # Get {tax_level} profile data
    mpa4_profile = pd.read_table(
        f"{data_root_dir}/mpa4_{tax_level}.profile", sep="\t", header=0, index_col=0
    )
    # Remove {tax_level} with no reads
    mpa4_profile = mpa4_profile.loc[:, mpa4_profile.sum(axis=0) >= 1]

    ## Remove repeated samples
    logger.info(f"sample_group_useful.shape before removal: {sample_group.shape}")
    sample_group = sample_group[~sample_group.index.duplicated(keep="first")]
    logger.info(f"sample_group_useful.shape after removal: {sample_group.shape}")

    # remove samples not in sample_group
    logger.info(
        f"mpa4_{tax_level}_profile.shape before filtering out samples without metadata: {mpa4_profile.shape}"
    )
    samples_to_keep = list(
        set(sample_group.index.tolist()) & set(mpa4_profile.columns.tolist())
    )
    mpa4_profile = mpa4_profile[samples_to_keep]
    logger.info(
        f"mpa4_{tax_level}_profile.shape after filtering out samples without metadata: {mpa4_profile.shape}"
    )
    mpa4_profile = mpa4_profile.T
    logger.info(
        f"mpa4_{tax_level}_profile.shape after transposing: {mpa4_profile.shape}"
    )

    # remove samples from sample_group that are not in mpa4_{tax_level}_profile
    logger.info(
        f"sample_group_useful.shape before filtering out samples not in mpa4_{tax_level}_profile: {sample_group.shape}"
    )
    sample_group = sample_group.loc[samples_to_keep]
    logger.info(
        f"sample_group_useful.shape after filtering out samples not in mpa4_{tax_level}_profile: {sample_group.shape}"
    )

    extra_mp4a_profile = pd.DataFrame()
    extra_sample_group = pd.DataFrame()
    if augment_data:
        grouped_sample_group = sample_group.groupby("Project_1")
        for group, samples in grouped_sample_group.groups.items():
            group_data = mpa4_profile.loc[samples]
            group_metadata = sample_group.loc[samples]
            # Aitchison Mixup
            mpa4_profile_new, sample_group_new_labels, _ = aitchison_mixup(
                group_data.values,
                group_metadata["Group"],
                n_aug_per_class=2500,
                weight=0.5,
            )

            new_mpa4_profile = pd.DataFrame(
                mpa4_profile_new, columns=group_data.columns
            )
            new_sample_group = pd.DataFrame(sample_group_new_labels, columns=["Group"])
            new_sample_group["Project_1"] = pd.Series([group] * new_sample_group.shape[0], index=new_sample_group.index)
            extra_mp4a_profile = pd.concat(
                [extra_mp4a_profile, new_mpa4_profile], axis=0, ignore_index=True
            )
            extra_sample_group = pd.concat(
                [extra_sample_group, new_sample_group], axis=0, ignore_index=True
            )
            

    if do_prevalence_and_abundance_filtering:
        # Normalize the data
        logger.info(
            f"mpa4_{tax_level}_profile summation before normalization: {mpa4_profile.sum(axis=1)}"
        )
        mpa4_profile = preprocessing_functions.total_sum_scaling(mpa4_profile)
        logger.info(
            f"mpa4_{tax_level}_profile summation after normalization: {mpa4_profile.sum(axis=1)}"
        )
        # prevalence and abundance filtering
        # low abundance filtering per study
        # Should we skip filtering?
        grouped_sample_group = sample_group.groupby("Project_1")

        for project, samples in grouped_sample_group.groups.items():
            logger.info(f"Project: {project}")
            rows_to_update = mpa4_profile.loc[samples]
            feature_prevalence = (rows_to_update > abundance_filtering_threshold).sum(
                axis=0
            ) / rows_to_update.shape[0]
            low_abundance_features = feature_prevalence < 0.1

            df_masked = rows_to_update.mask(
                low_abundance_features
                | (rows_to_update <= abundance_filtering_threshold),
                0,
            )
            mpa4_profile.update(df_masked)
        

    if normalize_and_transform:
        # normalize and transform
        logger.info(
            f"mpa4_{tax_level}_profile summation before normalization: {mpa4_profile.sum(axis=1)}"
        )
        mpa4_profile = preprocessing_functions.total_sum_scaling(mpa4_profile)
        extra_mp4a_profile = preprocessing_functions.total_sum_scaling(extra_mp4a_profile)

        logger.info(
            f"mpa4_{tax_level}_profile summation after normalization: {mpa4_profile.sum(axis=1)}"
        )

        # Centered arcsine transform
        logger.info(
            f"mpa4_{tax_level}_profile summation before centered arcsine transform: {mpa4_profile.sum(axis=1)}"
        )
        mpa4_profile = preprocessing_functions.centered_arcsine_transform(mpa4_profile)
        extra_mp4a_profile = preprocessing_functions.centered_arcsine_transform(extra_mp4a_profile)
        logger.info(
            f"mpa4_{tax_level}_profile summation after centered arcsine transform: {mpa4_profile.sum(axis=1)}"
        )

    # Save the data
    # mpa4_profile.to_csv(f"{data_root_dir}/mpa4_{tax_level}_{title_addition}.csv")
    # sample_group.to_csv(
    #     f"{data_root_dir}/sample_group_{tax_level}_{title_addition}.csv"
    # )
    if not extra_mp4a_profile.empty:
        extra_mp4a_profile.to_csv(
            f"{data_root_dir}/augmented/mpa4_{tax_level}_{title_addition}_aitchison.csv"
        )
        extra_sample_group.to_csv(
            f"{data_root_dir}/augmented/sample_group_{tax_level}_{title_addition}_aitchison.csv"
        )


if __name__ == "__main__":
    preprocess_data(
        do_prevalence_and_abundance_filtering=True,
        normalize_and_transform=True,
        title_addition="preprocessed",
        tax_level="species",
        augment_data=True,
    )
