misc:
  base_data_dir: "data"  # relative path of parent data directory from the root of the project
  wandb: true
  verbose_pipeline: true
  cache_pipeline_steps: true

# This step will be simplified as data should be downloaded separately. It is a bit involved and putting it in a separate pipeline is better.
data:
  # Leave out if all studies desired; if provided, only the summaries of those studies are downloaded
  # if studies are given, they have to contain the desired summary given by study_download_label_start
  study_accessions:
    - ""
    - ""
  # indicates what summary file to download for the studies
  # possible values:
        # - Complete GO
        # - GO slim
        # - Phylum level (this results in downloading all possibilities, e.g. SSU, LSU, ...)
        # - Phylum level taxonomies SSU
        # - Taxonomic assignments SSU
        # - InterPro
        # - Taxonomic diversity metrics SSU
        # ... (see MGnify API)
  study_download_label_start: ""
  # The biome to get the studies for.
  # Leave out if all studies are desired
  # The strings can also just be a part of the biome name.
  biomes_desired:
  # Whether to download metadata for the studies
  download_metadata: true
  # Whether to add the metadata to the summary data
  use_metadata: true
  train_test_split:
    - 0.8
    - 0.2
  # Used for hyperparameter optimization
  cross_val_k: 10
  # Used for early stopping
  val_size: 0.1

preprocessing:  # the order is followed as it is given
  # possible values: 
  batch_effect_corrections:
    - ""
    - ""
  # possible values:
  imputations:
    - ""
    - ""
  # possible values:
  # scikit-bio used
  normalization_and_transformations:
    - ""
    - ""
  # possible values:
  feature_space_change: 

model:
# possible values:  RandomForestClassifier 
  type: ""
  params:
    - "": ""
    - "": ""
  # possible values: 
  # maybe each needs also its own params (in that case separating from model is better)
  eval_metrics:
    - ""
    - ""


